spring:
  profiles:
    default: dev
    
---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: strife
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}

---

spring:
  config:
    activate:
      on-profile: test
  application:
    name: strife-test

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.0
        storage:
          repl-set-name: rs0