spring:
    application:
        name: strife
    data:
        mongodb:
            database: ${MONGO_DATABASE}
            uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.0